<?php

namespace AppBundle\Repository;

/**
 * CoursePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
