<?php

namespace AppBundle\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{

  public function getEnabled()
  {
    return $this->createQueryBuilder('r')
        ->where('r.enabled = true');
//    return $this->findBy(['enabled' => true]);
  }

}
