<?php

namespace AppBundle\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorRepository extends \Doctrine\ORM\EntityRepository
{

  public function queryEnabled()
  {
    return $this->createQueryBuilder('t')
            ->where('t.enabled = true');
  }

}
