#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    type:     yml
#    prefix:   /backend
#    schemes:  ['%httpprotocol%']

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    schemes:  ['%httpprotocol%']
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes:  ['%httpprotocol%']
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    schemes:  ['%httpprotocol%']
    
# config/routes/sonata_admin.yaml

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /backend

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /backend

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /backend

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /backend/resetting