app:
    resource: '@AppBundle/Controller/'
    type: annotation
    schemes:  ['%httpprotocol%']
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes:  ['%httpprotocol%']
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    schemes:  ['%httpprotocol%']