services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
            
    backend.admin.room:
        class: BackendBundle\Admin\RoomAdmin
        arguments: [~, AppBundle\Entity\Room, BackendBundle\Controller\RoomAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Room }
        public: true

    backend.admin.instrument:
        class: BackendBundle\Admin\InstrumentAdmin
        arguments: [~, AppBundle\Entity\Instrument, BackendBundle\Controller\InstrumentAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Instrument }
        public: true

    backend.admin.tutor:
        class: BackendBundle\Admin\TutorAdmin
        arguments: [~, AppBundle\Entity\Tutor, BackendBundle\Controller\TutorAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tutor }
        public: true
