services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    backend.scheduler.customer:
        class: BackendBundle\Admin\CustomerAdmin
        arguments: [~, AppBundle\Entity\Customer, BackendBundle\Controller\CustomerAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reservation, label: Customer }
        public: true

    backend.scheduler.reservation:
        class: BackendBundle\Admin\ReservationAdmin
        arguments: [~, AppBundle\Entity\Reservation, BackendBundle\Controller\ReservationAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reservation, label: Reservation }
        public: true
        
    backend.admin.availability:
        class: BackendBundle\Admin\AvailabilityAdmin
        arguments:
            - ~
            - ~
            - BackendBundle\Controller\AvailabilityAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reservation, label: Availability }
            
    backend.admin.tutors:
        class: BackendBundle\Admin\RoomAdmin
        arguments: [~, AppBundle\Entity\Room, BackendBundle\Controller\RoomAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reports, label: Tutors  }
        public: true
        
    backend.admin.room:
        class: BackendBundle\Admin\RoomAdmin
        arguments: [~, AppBundle\Entity\Room, BackendBundle\Controller\RoomAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Room }
        public: true

    backend.admin.instrument:
        class: BackendBundle\Admin\InstrumentAdmin
        arguments: [~, AppBundle\Entity\Instrument, BackendBundle\Controller\InstrumentAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Instrument }
        public: true

    backend.admin.tutor:
        class: BackendBundle\Admin\TutorAdmin
        arguments: [~, AppBundle\Entity\Tutor, BackendBundle\Controller\TutorAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Tutor }
        public: true

    backend.admin.course:
        class: BackendBundle\Admin\CourseAdmin
        arguments: [~, AppBundle\Entity\Course, BackendBundle\Controller\CourseAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Course }
        public: true

    backend.admin.course_price:
        class: BackendBundle\Admin\CoursePriceAdmin
        arguments: [~, AppBundle\Entity\CoursePrice, BackendBundle\Controller\CoursePriceAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: CoursePrice }
        public: true

#    backend.admin.config:
#        class: BackendBundle\Admin\ConfigAdmin
#        arguments: [~, AppBundle\Entity\Config, BackendBundle\Controller\ConfigAdminController]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Admin, label: Config }
#        public: true

    backkend.admin.working_hours:
        class: BackendBundle\Admin\WorkingHoursAdmin
        arguments:
            - ~
            - ~
            - BackendBundle\Controller\WorkingHoursCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Working Hours}
            
   