services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     admin.instrument:
        class: BackendBundle\Controller\InstrumentAdmin
        arguments: [~, AppBundle\Entity\Instrument, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Instrument' }
            
     admin.room:
        class: BackendBundle\Controller\RoomAdmin
        arguments: [~, AppBundle\Entity\Room, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Room' }